name: Call Deploy AKS Arc Workflow
run-name: ${{ github.actor }} is going to call deploy workflow

on:
  workflow_dispatch:
    inputs:
      cluster-name:
        description: 'Name of the AKS Arc cluster'
        required: true
      resource-group:
        description: 'Azure Resource Group'
        required: true
      custom-location:
        description: 'Azure Local Custom Location'
        required: true
      vnet-id:
        description: 'Azure Local Logical Network id'
        required: true
      k8s-version:
        description: 'Kubernetes Version'
        required: false
        default: '1.30.4'
      git_ref:
        description: 'Git branch or tag to deploy'
        required: true
        type: string
        default: 'main'
      environment: # Added input parameter
        description: 'Choose deployment environment: production or staging'
        required: true
        type: string
        default: 'production'

jobs:
  enable-ui:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Starting AKS Arc deployment via reusable workflow..."

  call-deploy:
    uses: ./.github/workflows/deploy-aksarc.yml
    needs: enable-ui
    with:
      cluster-name: ${{ github.event.inputs.cluster-name }}
      resource-group: ${{ github.event.inputs.resource-group }}
      custom-location: ${{ github.event.inputs.custom-location }}
      vnet-id: ${{ github.event.inputs.vnet-id }}
      k8s-version: ${{ github.event.inputs.k8s-version }}
      git_ref: ${{ github.event.inputs.git_ref }}
      environment: ${{ github.event.inputs.environment }}
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
      GITOPS_PUSH_PAT: ${{ secrets.GITOPS_PUSH_PAT }}
