name: Deploy AKS Arc on Azure Local
run-name: ${{ github.actor }} is deploying an AKS Arc cluster 🚀
on:
  workflow_call:
    inputs:
      cluster-name:
        required: true
        type: string
      resource-group:
        required: true
        type: string
      custom-location:
        required: true
        type: string
      vnet-id:
        required: true
        type: string
      k8s-version:
        required: false
        type: string
        default: "1.30.4"
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_CLIENT_SECRET:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: |
            {
              "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
              "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
              "tenantId": "${{ secrets.AZURE_TENANT_ID }}",
              "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
            }
#          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create AKS Arc Cluster
        run: |
          az extension add --name aksarc
          az aksarc create \
            --name ${{ inputs.cluster-name }} \
            --resource-group ${{ inputs.resource-group }} \
            --custom-location ${{ inputs.custom-location }} \
            --vnet-id ${{ inputs.vnet-id }} \
            --control-plane-node-count 1 \
            --worker-node-count 1 \
            --kubernetes-version "${{ inputs.k8s-version }}" \
            --generate-ssh-keys \
            --aad-admin-group-object-ids "be0c17dc-9a37-48c5-9691-751a27a4c1b9,f5157bd2-8ce4-48b6-82df-69b9de7540a9,af0ac67a-fcb3-4c19-a950-c32f938ee163"
#            --ssh-public-key "$(cat ~/.ssh/id_rsa.pub)"

#      - name: Get kubeconfig
#        run: |
#          az aksarc get-credentials \
#            --name ${{ inputs.cluster-name }} \
#            --resource-group ${{ inputs.resource-group }}

