name: Upgrade AKS Arc Cluster Workflow
run-name: ${{ github.actor }} is going to call deploy workflow

on:
  workflow_dispatch:
    inputs:
      cluster-name:
        description: 'Name of the AKS Arc cluster'
        required: true
      resource-group:
        description: 'Azure Resource Group'
        required: true
      k8s-version:
        description: 'Kubernetes Version'
        required: false
        default: '1.30.4'

jobs:
  enable-ui:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Starting AKS Arc upgrade ..."

  Upgrade-aksarc-cluster:
    needs: enable-ui
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: |
            {
              "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
              "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
              "tenantId": "${{ secrets.AZURE_TENANT_ID }}",
              "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
            }
#          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Upgrade Azure CLI
        run: |
          az upgrade --yes

      - name: Upgrade AKS Arc Cluster
        run: |
          az extension add --name aksarc
          az aksarc upgrade \
            --name ${{ inputs.cluster-name }} \
            --resource-group ${{ inputs.resource-group }} \
            --kubernetes-version "${{ inputs.k8s-version }}"    
